# Server polling frequency in seconds
queryFrequency: 10
baseURL: http://gos.validator.network:26657/
validatorNetworkAddress: 01F78669F9515FD83DF9250F5C0EE143D3DAD65C
# prometheusURL: 0.0.0.0:8080 # Defaults to [::]:26662